HEADERS += \
	russianC/elementGeneratorFactory.h \
	russianC/russianCRobotGenerator.h \
	russianC/smartLine.h \
	russianC/generators/abstractElementGenerator.h \
	russianC/generators/functionElementGenerator.h \
	russianC/generators/ifElementGenerator.h \
	russianC/generators/loopElementGenerator.h \
	russianC/generators/simpleElementGenerator.h \
	russianC/generators/simpleElements/abstractSimpleElementGenerator.h \
	russianC/generators/simpleElements/enginesStopGenerator.h \
	russianC/generators/simpleElements/timerGenerator.h \
	russianC/generators/simpleElements/beepGenerator.h \
	russianC/generators/simpleElements/playToneGenerator.h \
	russianC/generators/simpleElements/finalNodeGenerator.h \
	russianC/generators/simpleElements/nullificationEncoderGenerator.h \
	russianC/generators/simpleElements/initialBlockGenerator.h \
	russianC/generators/simpleElements/waitForColorBlockGenerator.h \
	russianC/generators/simpleElements/waitForColorIntensityBlockGenerator.h \
	russianC/generators/simpleElements/balanceGenerator.h \
	russianC/generators/simpleElements/waitForLightBlockGenerator.h \
	russianC/generators/simpleElements/waitForSonarBlockGenerator.h \
	russianC/generators/simpleElements/waitForEncoderBlockGenerator.h \
	russianC/generators/simpleElements/waitForTouchSensorBlockGenerator.h \
	russianC/generators/simpleElements/variableInitGenerator.h \
	russianC/generators/simpleElements/balanceInitGenerator.h \
	russianC/generators/simpleElementFactory.h \
	russianC/generators/simpleElements/initialNodeGenerator.h \
	russianC/generators/simpleElements/enginesGenerator.h \
	russianC/generators/listsmartline.h \

SOURCES += \
	russianC/elementGeneratorFactory.cpp \
	russianC/russianCRobotGenerator.cpp \
	russianC/smartLine.cpp \
	russianC/generators/abstractElementGenerator.cpp \
	russianC/generators/functionElementGenerator.cpp \
	russianC/generators/ifElementGenerator.cpp \
	russianC/generators/loopElementGenerator.cpp \
	russianC/generators/simpleElementGenerator.cpp \
	russianC/generators/simpleElements/abstractSimpleElementGenerator.cpp \
	russianC/generators/simpleElements/enginesStopGenerator.cpp \
	russianC/generators/simpleElements/timerGenerator.cpp \
	russianC/generators/simpleElements/beepGenerator.cpp \
	russianC/generators/simpleElements/playToneGenerator.cpp \
	russianC/generators/simpleElements/finalNodeGenerator.cpp \
	russianC/generators/simpleElements/nullificationEncoderGenerator.cpp \
	russianC/generators/simpleElements/initialBlockGenerator.cpp \
	russianC/generators/simpleElements/waitForColorBlockGenerator.cpp \
	russianC/generators/simpleElements/waitForColorIntensityBlockGenerator.cpp \
	russianC/generators/simpleElements/balanceGenerator.cpp \
	russianC/generators/simpleElements/waitForLightBlockGenerator.cpp \
	russianC/generators/simpleElements/waitForSonarBlockGenerator.cpp \
	russianC/generators/simpleElements/waitForEncoderBlockGenerator.cpp \
	russianC/generators/simpleElements/waitForTouchSensorBlockGenerator.cpp \
	russianC/generators/simpleElements/variableInitGenerator.cpp \
	russianC/generators/simpleElements/balanceInitGenerator.cpp \
	russianC/generators/simpleElementFactory.cpp \
	russianC/generators/simpleElements/initialNodeGenerator.cpp \
	russianC/generators/simpleElements/enginesGenerator.cpp \
	russianC/generators/listsmartline.cpp \
