HEADERS += \
	russianC/russianCRobotGenerator.h \
	russianC/rcSmartLine.h \
	russianC/rcElementGeneratorFactory.h \
	russianC/generators/simpleElements/rcAbstractSimpleElementGenerator.h \
	russianC/generators/simpleElements/rcBalanceGenerator.h \
	russianC/generators/simpleElements/rcBalanceInitGenerator.h \
	russianC/generators/simpleElements/rcBeepGenerator.h \
	russianC/generators/simpleElements/rcEnginesGenerator.h \
	russianC/generators/simpleElements/rcEnginesStopGenerator.h \
	russianC/generators/simpleElements/rcFinalNodeGenerator.h \
	russianC/generators/simpleElements/rcInitialBlockGenerator.h \
	russianC/generators/simpleElements/rcInitialNodeGenerator.h \
	russianC/generators/simpleElements/rcNullificationEncoderGenerator.h \
	russianC/generators/simpleElements/rcPlayToneGenerator.h \
	russianC/generators/simpleElements/rcTimerGenerator.h \
	russianC/generators/simpleElements/rcVariableInitGenerator.h \
	russianC/generators/simpleElements/rcWaitForColorBlockGenerator.h \
	russianC/generators/simpleElements/rcWaitForColorIntensityBlockGenerator.h \
	russianC/generators/simpleElements/rcWaitForLightBlockGenerator.h \
	russianC/generators/simpleElements/rcWaitForSonarBlockGenerator.h \
	russianC/generators/simpleElements/rcWaitForTouchSensorBlockGenerator.h \
	russianC/generators/rcAbstractElementGenerator.h \
	russianC/generators/rcFunctionElementGenerator.h \
	russianC/generators/rcIfElementGenerator.h \
	russianC/generators/rcListsmartline.h \
	russianC/generators/rcLoopElementGenerator.h \
	russianC/generators/rcSimpleElementFactory.h \
	russianC/generators/rcSimpleElementGenerator.h \
	russianC/generators/simpleElements/rcWaitForEncoderBlockGenerator.h

SOURCES += \
	russianC/generators/simpleElements/rcAbstractSimpleElementGenerator.cpp \
	russianC/generators/simpleElements/rcBalanceGenerator.cpp \
	russianC/generators/simpleElements/rcBalanceInitGenerator.cpp \
	russianC/generators/simpleElements/rcBeepGenerator.cpp \
	russianC/generators/simpleElements/rcEnginesGenerator.cpp \
	russianC/generators/simpleElements/rcEnginesStopGenerator.cpp \
	russianC/generators/simpleElements/rcFinalNodeGenerator.cpp \
	russianC/generators/simpleElements/rcInitialBlockGenerator.cpp \
	russianC/generators/simpleElements/rcInitialNodeGenerator.cpp \
	russianC/generators/simpleElements/rcNullificationEncoderGenerator.cpp \
	russianC/generators/simpleElements/rcPlayToneGenerator.cpp \
	russianC/generators/simpleElements/rcTimerGenerator.cpp \
	russianC/generators/simpleElements/rcVariableInitGenerator.cpp \
	russianC/generators/simpleElements/rcWaitForColorBlockGenerator.cpp \
	russianC/generators/simpleElements/rcWaitForColorIntensityBlockGenerator.cpp \
	russianC/generators/simpleElements/rcWaitForEncoderBlockGenerator.cpp \
	russianC/generators/simpleElements/rcWaitForLightBlockGenerator.cpp \
	russianC/generators/simpleElements/rcWaitForSonarBlockGenerator.cpp \
	russianC/generators/simpleElements/rcWaitForTouchSensorBlockGenerator.cpp \
	russianC/generators/rcAbstractElementGenerator.cpp \
	russianC/generators/rcFunctionElementGenerator.cpp \
	russianC/generators/rcIfElementGenerator.cpp \
	russianC/generators/rcListsmartline.cpp \
	russianC/generators/rcLoopElementGenerator.cpp \
	russianC/generators/rcSimpleElementFactory.cpp \
	russianC/generators/rcSimpleElementGenerator.cpp \
	russianC/rcElementGeneratorFactory.cpp \
	russianC/rcSmartLine.cpp \
	russianC/russianCRobotGenerator.cpp
